# mac = Apple PowerBook G4 laptop, c++, no MPI

SHELL = /bin/sh

# System-specific settings

CC =		c++
CCFLAGS =	-O -MMD -I../STUBS 
LINK =		c++
LINKFLAGS =	-O 
USRLIB =	../STUBS/mpi.o
SYSLIB = 
SIZE =		size

# Test rule

test:
	$(EXE) < $(INPUTFILE)

# Link rule

$(EXE):	$(OBJ)
	$(LINK) $(LINKFLAGS) $(OBJ) $(USRLIB) $(SYSLIB) -o $(EXE)
	$(SIZE) $(EXE)

# Compilation rules


%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
-include $(DEPENDS)
